### ISSUE TITLE
rspec with redstorm : uninitialized constant RedStorm::SimpleBolt::Values

### ISSUE THREAD

**Issue by stonegao** [colinsurprenant/redstorm#17]
This may related to the classpath issue. I have tried run `CLASSPATH="./target/dependency/*"` but still got the following error: 

<pre>
     NameError:
       uninitialized constant RedStorm::SimpleBolt::Values
</pre>

**Comment by colinsurprenant** [comment]
Stone,

are you trying to run the specs on redstorm project itself or specs of your own project using redstorm?

**Comment by stonegao** [comment]
My own project using redstorm.

**Comment by stonegao** [comment]
`jruby -J-cp "target/dependency/*" -S  rspec ./spec/` also not works. the same error. Maybe it's time to create a redstorm-starter project to demonstrate  the usage of redstorm with specs.

**Comment by colinsurprenant** [comment]
redstorm-starter is a good idea. 
For the specs, I believe this is because the Backtype (Java) classes are not defined when running the specs. You can probably mock theses classes in your test for now. I am not sure what is the best approach for this globally at this point. Maybe provide a set of mocks for specs? I am not sure, I will have to research a bit more about this to see if there are some "best practices" in JRuby in regards to specs with references to Java classes etc.

**Comment by colinsurprenant** [comment]
as an example, I am including the backtype.storm.tuple.Values class in the `spec/red_storm/dsl/tuple_spec` (in v0.6.6 branch and forward).

I am first requiring the jars in spec_helper.rb with 

``` ruby
storm_jars = File.dirname(__FILE__) + '/../target/dependency/storm/default/*.jar'
Dir.glob(storm_jars).each{|f| require f}
```

this is equivalent to specifying the jars in the classpath.

then including the Values class

``` ruby
java_import 'backtype.storm.tuple.Values'
```

**Comment by colinsurprenant** [comment]
I have created a redstorm-starter https://github.com/colinsurprenant/redstorm-starter/ project which include example specs for bolts and complete topology.
