### ISSUE TITLE
add support for external Jars

### ISSUE THREAD

**Issue by fractaloop** [colinsurprenant/redstorm#48]
Some topologies may require external jars, such as the ones in [storm-contrib](https://github.com/nathanmarz/storm-contrib). A mechanism is needed to specify jars/files/etc that will get included during `redstorm deps`

**Comment by fractaloop** [comment]
Currently I'm unpacking them so they get JARed up with jruby, which works. We'll need a way to ensure they are in Java classpath (external to the embedded JRuby).

**Comment by colinsurprenant** [comment]
Thanks for your work & perseverance on this, very useful feature.

**Comment by colinsurprenant** [comment]
Here's my idea for this. First I want to allow an external dependency specification which will overrides the default one. If the file `Dependencies` is present in the project root, it will be used to specify the dependencies. The syntax is a Ruby hash to specify the PomPomPom::Runner configuration. 

For example, to reproduce @fractaloop KafkaSpout use-case, I created the following `Dependencies` file which basically adds the storm-kafka, kafka, scala-library jars to the default dependencies.

``` ruby
{
  :repositories => {:clojars => 'http://clojars.org/repo/', :sonatype => "http://oss.sonatype.org/content/groups/public/"},
  :dependencies => [
    "storm:storm:0.8.1|type_filter=jar",
    "org.slf4j:slf4j-log4j12:1.5.8|type_filter=jar",
    "org.jruby:jruby-complete:1.6.8|transitive=false,type_filter=jar",
    "storm:storm-kafka:0.8.0-wip4|transitive=false,type_filter=jar",
    "storm:kafka:0.7.0-incubating|transitive=false,type_filter=jar",
    "org.scala-lang:scala-library:2.8.0|transitive=false,type_filter=jar",
  ],
  :destination => TARGET_DEPENDENCY_DIR
}
```

This works in local mode but it does not work in cluster mode because when creating the topology jar, external jars we want to include must be unpacked to be able to create a single topology submission jar that contains all the classes/resources/etc.

What I Iike about exposing the dependencies config is that it gives full control but I am not sure how to deal with 
1- specifying wich jar need to be unpacked and included in the topology submission jar
2- including local/"non-maven" jar files in the project. 

For 1 maybe we could have 2 dependencies config, one for jars that need to be repackaged into the topology jar and one for the other?

For 2 maybe just "manually" copy the jars in the right directory depending if it needs to be repackaged or not?

Any thoughts?

CC @iconara

**Comment by colinsurprenant** [comment]
Ok, I changed a few things. I replaced pompompom with ant+ivy. I went with my idea of an externalized dependencies config file "Dependencies" with 2 parts: the storm dependencies (basically the storm jar for running in local mode) and the topology dependencies, all other jars required to run a topology. If the "Dependencies" file is not present then the defaults are the storm and jruby jars. For now, its a simple Ruby hash.

Here's a Dependencies example for using Kafka: 

``` ruby
{
  :storm_artifacts => [
    "storm:storm:0.8.1, transitive=true",
  ],
  :topology_artifacts => [
    "org.jruby:jruby-complete:1.6.8, transitive=false",
    "org.scala-lang:scala-library:2.8.0, transitive=false",
    "storm:kafka:0.7.0-incubating, transitive=false",
    "storm:storm-kafka:0.8.0-wip4, transitive=false",
  ],
}
```

Also, the ivy maven sources can be managed using the `ivy/settings.xml` file. I'll see if I can setup these sources programatically and change the xml config for a Ruby config file.

@fractaloop if you could give this a spin to see if it work with your environment I would appreciate!

**Comment by fractaloop** [comment]
This seems to work great! Thanks for your awesome work.
