### ISSUE TITLE
Bundling jdbc/postgresql with topology

### ISSUE THREAD

**Issue by stefan-pdx** [colinsurprenant/redstorm#81]
Hey guys,

I'm having trouble using the jdbc-postgres gem within a topology. I know that the gem distributes the corresponding JDBC interface (.jar files) with the gem, however, it appears not to be properly loading. 

Step 1: Configure the Gemfile

``` ruby
source 'https://rubygems.org'

gem 'redstorm', '0.6.5'

group :database do
  gem 'jdbc-postgres', '~> 9.2.1002.1', :platform => :jruby
end
```

Step 2: Install deps

```
bundle install --path vendor/bundle
bundle exec redstorm install
bundle exec redstorm bundle install database
```

Step 3: Running the topology

```
bundle exec redstorm local database_topology.rb
```

Errors out with:

```
Message: No suitable driver found for jdbc:postgresql://localhost/database; StackTrace: java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost/database
```

My topology is defined as:

``` ruby
require 'red_storm'
require 'jdbc/postgres'

module RedStorm
  module Examples
    class DatabaseSpout < RedStorm::SimpleSpout
      output_fields :dummy
      on_init do
        Jdbc::Postgres.load_driver && org.postgresql.Driver
        java.sql.DriverManager.get_connection("jdbc:postgresql://localhost/database", nil, nil)
      end
      on_send {}
    end

    class DatabaseTopology < RedStorm::SimpleTopology
      spout DatabaseSpout

      configure do |env|
        debug true
      end

      on_submit do |env|
        if env == :local
          sleep(5)
          cluster.shutdown
        end
      end
    end
  end
end
```

The jdbc-postgres gem can be loaded in a corresponding IRB session (`bundle exec irb`):

``` ruby
>> require 'jdbc/postgres'
=> true
>> Jdbc::Postgres.load_driver && org.postgresql.Driver
=> Java::OrgPostgresql::Driver
>> java.sql.DriverManager.get_connection("jdbc:postgresql://localhost/database", nil, nil)
=> #<Java::OrgPostgresqlJdbc4::Jdbc4Connection:0x6db1358d>
```

I'm not too familiar how/if RedStorm performs referencing/bundling of jar files inside of gems. Can anyone provide insight into why this wouldn't work as expected?

**Comment by colinsurprenant** [comment]
clearly, jars cannot be referenced within a jar. as a possible quick workaround can you copy the jdbc jar into target/dependency/topology/default and try it?

**Comment by colinsurprenant** [comment]
did you finally make it work?

**Comment by colinsurprenant** [comment]
Sorry for the delay. I just spent some time trying to understand the issue here. 

There is clearly something fishy going on at the Java classloading level within Storm at the workers which screws the java.sql.DriverManager but I can't seem to pinpoint the problem yet. I can't reproduce the problem outside the Storm context either.

The temporary workaround is to copy `target/gems/gems/jdbc-postgres-9.2.1002.1/lib/postgresql-9.2-1002.jdbc4.jar` into `target/dependency/topology/default`

This also raises the issue of dealing with jars included in gems when submitting a cluster topology which will probably result in the jar-in-a-jar problem. I will have to test this.

created issue #86 for this.

**Comment by colinsurprenant** [comment]
Actually nothing to do with Storm, its basically a deficiency in DriverManager «DriverManager will only find drivers on the JVM's system classpath» and the driver is actually loaded from JRuby classloader - all explained here https://jira.codehaus.org/browse/JRUBY-7174

Another workaround which does not imply copying the jar is to directly use the driver instead of going through the DriverManager:

``` ruby
on_init do
  Jdbc::Postgres.load_driver
  connection = org.postgresql.Driver.new.connect("jdbc:postgresql://localhost/database", java.util.Properties.new)
end
```

I just tested in both local mode and on a cluster and both report "Connection refused" so driver is correctly working.
